---@meta

-- CrossPoint Lua API stub for LuaLS. GENERATED by scripts/gen_lua_stubs.py
-- from the annotations in src/util/lua/LuaBindings*.cpp; do not edit by hand.

---@alias CrossPointButton
---| "back"
---| "confirm"
---| "left"
---| "right"
---| "up"
---| "down"
---| "page_back"
---| "page_forward"

---@alias CrossPointOrientation
---| "portrait"
---| "portrait_inv"
---| "landscape_cw"
---| "landscape_ccw"

---@class ble
ble = {}

---@class fs
fs = {}

---@class gui
---@field HINT_BACK string
---@field HINT_OK string
---@field HINT_PREV string
---@field HINT_NEXT string
gui = {}
gui.HINT_BACK = "<<"
gui.HINT_OK = "o"
gui.HINT_PREV = "<"
gui.HINT_NEXT = ">"

---@class http
http = {}

---@class input
input = {}

---@class log
log = {}

---@class sys
sys = {}

---@class timer
timer = {}

---@class wifi
wifi = {}

---@type integer
COLOR_BLACK = 0
---@type integer
COLOR_CLEAR = 0
---@type integer
COLOR_DARK_GRAY = 0
---@type integer
COLOR_LIGHT_GRAY = 0
---@type integer
COLOR_WHITE = 0
---@type integer
FONT_BOOKERLY_12 = 0
---@type integer
FONT_BOOKERLY_14 = 0
---@type integer
FONT_BOOKERLY_16 = 0
---@type integer
FONT_NOTOSANS_12 = 0
---@type integer
FONT_NOTOSANS_14 = 0
---@type integer
FONT_NOTOSANS_16 = 0
---@type integer
FONT_SMALL = 0
---@type integer
FONT_UI_10 = 0
---@type integer
FONT_UI_12 = 0
---@type integer
REFRESH_FAST = 0
---@type integer
REFRESH_FULL = 0
---@type integer
REFRESH_HALF = 0
---@type integer
STYLE_BOLD = 0
---@type integer
STYLE_NORMAL = 0
---@type integer
STYLE_REGULAR = 0

-- ble

--- Connects to a BLE device by address.
---@param address string BLE address (e.g. "AA:BB:CC:DD:EE:FF")
---@return boolean ok
function ble.connect(address) end

--- Deinitializes the BLE stack, releasing resources.
function ble.deinit() end

--- Disconnects from the current BLE device.
function ble.disconnect() end

--- Initializes the BLE stack. Call before any other BLE operation.
---@param name? string Local device name (default "CrossPoint")
---@return boolean ok
function ble.init(name) end

--- Returns whether connected to a BLE device.
---@return boolean connected
function ble.isConnected() end

--- Reads a BLE characteristic value.
---@param serviceUUID string Service UUID (e.g. "0000180f-0000-1000-8000-00805f9b34fb")
---@param charUUID string Characteristic UUID
---@return string? value Characteristic value as string, nil on failure
function ble.read(serviceUUID, charUUID) end

--- Scans for BLE devices and returns a table of results.
---@param duration? integer Scan duration in milliseconds (default 3000)
---@return table results Array of { name: string, address: string, rssi: int }
function ble.scan(duration) end

--- Starts advertising this device as a BLE peripheral.
---@param name? string Advertised name (default "CrossPoint")
---@return boolean ok
function ble.startAdvertising(name) end

--- Stops BLE advertising.
function ble.stopAdvertising() end

--- Writes a value to a BLE characteristic.
---@param serviceUUID string Service UUID
---@param charUUID string Characteristic UUID
---@param value string Value to write
---@return boolean ok
function ble.write(serviceUUID, charUUID, value) end

-- fs

--- Returns true if a file or directory exists.
---@param path string Absolute path on the SD card
---@return boolean
function fs.exists(path) end

--- Returns the size of a file in bytes.
---@param path string Absolute path on the SD card
---@return integer? size Nil if the file is missing or a directory
function fs.fileSize(path) end

--- Lists sorted sub-directory names under a path (hidden entries excluded).
---@param path string Absolute path on the SD card
---@return string[] names
function fs.listDirs(path) end

--- Lists sorted file names under a path (hidden entries excluded).
---@param path string Absolute path on the SD card
---@return string[] names
function fs.listFiles(path) end

--- Creates a directory.
---@param path string Absolute path on the SD card
---@return boolean? ok
---@return string? error Present when ok is nil
function fs.mkdir(path) end

--- Reads an entire file (capped at ~50KB).
---@param path string Absolute path on the SD card
---@return string? content Nil if the file is missing or unreadable
function fs.readFile(path) end

--- Reads the first full line beginning at or after a byte offset, for paging large files.
---@param path string Absolute path on the SD card
---@param offset integer Byte offset (0-based); snaps forward to the next line boundary if mid-line
---@return string? line Nil past end of file, or if the line exceeds 192 bytes
---@return integer? nextOffset Byte offset of the following line
function fs.readLineAt(path, offset) end

--- Deletes a file. /.apps and /.crosspoint are protected.
---@param path string Absolute path on the SD card
---@return boolean? ok
---@return string? error Present when ok is nil
function fs.remove(path) end

--- Recursively deletes a directory tree. /.apps and /.crosspoint are protected.
---@param path string Absolute path on the SD card
---@return boolean? ok
---@return string? error Present when ok is nil
function fs.removeTree(path) end

--- Renames (moves) a file or directory.
---@param source string
---@param destination string Must not already exist
---@return boolean? ok
---@return string? error Present when ok is nil
function fs.rename(source, destination) end

--- Writes a file (creating or overwriting).
---@param path string Absolute path on the SD card
---@param content string
---@return boolean ok
function fs.writeFile(path, content) end

-- gui

--- Clears the framebuffer to white.
function gui.clear() end

--- Draws a BMP file from the SD card, centered by default.
---@param path string Absolute path on the SD card
---@param x? integer Left edge (default centered)
---@param y? integer Top edge (default centered)
---@param maxWidth? integer Bounds the image is scaled into (default screen)
---@param maxHeight? integer Bounds the image is scaled into (default screen)
---@return boolean ok False if the file is missing or not a valid BMP
function gui.drawBmp(path, x, y, maxWidth, maxHeight) end

--- Draws the standard four-button hint bar (use gui.HINT_* for arrow glyphs).
---@param btn1? string Back button label (default "")
---@param btn2? string Confirm button label (default "")
---@param btn3? string Left button label (default "")
---@param btn4? string Right button label (default "")
function gui.drawButtonHints(btn1, btn2, btn3, btn4) end

--- Draws text centered horizontally on the screen.
---@param font integer FONT_* constant
---@param y integer Baseline Y
---@param text string
---@param color? integer COLOR_* constant (default COLOR_BLACK)
---@param style? integer STYLE_* constant (default STYLE_REGULAR)
function gui.drawCenteredText(font, y, text, color, style) end

--- Draws an unfilled circle.
---@param cx integer Center X
---@param cy integer Center Y
---@param radius integer
---@param width? integer Stroke width (default 1)
---@param color? integer COLOR_* constant (default COLOR_BLACK)
function gui.drawCircle(cx, cy, radius, width, color) end

--- Draws a line.
---@param x1 integer Start X
---@param y1 integer Start Y
---@param x2 integer End X
---@param y2 integer End Y
---@param width? integer Stroke width (default 1)
---@param color? integer COLOR_* constant (default COLOR_BLACK)
function gui.drawLine(x1, y1, x2, y2, width, color) end

--- Draws a single pixel.
---@param x integer
---@param y integer
---@param color? integer COLOR_* constant (default COLOR_BLACK)
function gui.drawPixel(x, y, color) end

--- Draws an unfilled rectangle.
---@param x integer Left edge
---@param y integer Top edge
---@param w integer Width
---@param h integer Height
---@param color? integer COLOR_* constant (default COLOR_BLACK)
function gui.drawRect(x, y, w, h, color) end

--- Draws an unfilled rounded rectangle.
---@param x integer Left edge
---@param y integer Top edge
---@param w integer Width
---@param h integer Height
---@param width? integer Stroke width (default 2)
---@param radius? integer Corner radius (default 10)
---@param color? integer COLOR_* constant (default COLOR_BLACK)
function gui.drawRoundedRect(x, y, w, h, width, radius, color) end

--- Draws text at a position.
---@param font integer FONT_* constant
---@param x integer Left edge
---@param y integer Baseline Y
---@param text string
---@param color? integer COLOR_* constant (default COLOR_BLACK)
---@param style? integer STYLE_* constant (default STYLE_REGULAR)
function gui.drawText(font, x, y, text, color, style) end

--- Draws a filled circle.
---@param cx integer Center X
---@param cy integer Center Y
---@param radius integer
---@param color? integer COLOR_* constant (default COLOR_BLACK)
function gui.fillCircle(cx, cy, radius, color) end

--- Draws a filled polygon from parallel vertex arrays (needs 3+ points).
---@param xs int[] X coordinates of each vertex
---@param ys int[] Y coordinates of each vertex
---@param color? integer COLOR_* constant (default COLOR_BLACK)
function gui.fillPolygon(xs, ys, color) end

--- Draws a filled rectangle.
---@param x integer Left edge
---@param y integer Top edge
---@param w integer Width
---@param h integer Height
---@param color? integer COLOR_* constant (default COLOR_BLACK)
function gui.fillRect(x, y, w, h, color) end

--- Draws a filled rounded rectangle.
---@param x integer Left edge
---@param y integer Top edge
---@param w integer Width
---@param h integer Height
---@param radius? integer Corner radius (default 10)
---@param color? integer COLOR_* constant (supports gray values) (default COLOR_BLACK)
function gui.fillRoundedRect(x, y, w, h, radius, color) end

--- Returns the rendered width of a string in pixels.
---@param font integer FONT_* constant
---@param text string
---@param style? integer STYLE_* constant (default STYLE_REGULAR)
---@return integer width
function gui.getTextWidth(font, text, style) end

--- Returns the screen height in pixels for the current orientation.
---@return integer
function gui.height() end

--- Pushes the framebuffer to the panel.
---@param mode? integer REFRESH_* constant (default REFRESH_FAST)
function gui.refresh(mode) end

--- Changes the screen orientation (invalidates any layout assumptions).
---@param mode string "portrait" | "portrait_inv" | "landscape_cw" | "landscape_ccw"
function gui.setOrientation(mode) end

--- Returns the screen width in pixels for the current orientation.
---@return integer
function gui.width() end

-- http

--- Performs an HTTP DELETE request.
---@param url string
---@param headers? table<string,string> Optional request headers
---@return string? body Nil on failure
---@return integer status HTTP status code, or -1 if the request never happened
function http.delete(url, headers) end

--- Downloads an HTTPS URL to a file with optional integrity checks.
---@param url string HTTPS URL
---@param destination string Absolute destination path on the SD card
---@param options table { maxBytes: int (required, up to 16MB), expectedSize?: int, sha256?: string (64 hex chars) }
---@return integer? bytesWritten Nil on failure
---@return string? error Present when the download fails
function http.download(url, destination, options) end

--- Performs an HTTP GET request.
---@param url string
---@param headers? table<string,string> Optional request headers
---@return string? body Nil on failure (capped at ~50KB)
---@return integer status HTTP status code, or -1 if the request never happened
function http.get(url, headers) end

--- Performs an HTTP HEAD request.
---@param url string
---@param headers? table<string,string> Optional request headers
---@return string? body Nil on failure
---@return integer status HTTP status code, or -1 if the request never happened
function http.head(url, headers) end

--- Performs an HTTP PATCH request.
---@param url string
---@param body? string Request body (default "")
---@param headers? table<string,string> Optional request headers
---@return string? body Nil on failure (capped at ~50KB)
---@return integer status HTTP status code, or -1 if the request never happened
function http.patch(url, body, headers) end

--- Performs an HTTP POST request.
---@param url string
---@param body? string Request body (default "")
---@param headers? table<string,string> Optional request headers
---@return string? body Nil on failure (capped at ~50KB)
---@return integer status HTTP status code, or -1 if the request never happened
function http.post(url, body, headers) end

--- Percent-encodes a string for use in a URL query.
---@param input string
---@return string encoded
function http.urlencode(input) end

-- input

--- Returns true while any button is currently held down.
---@return boolean
function input.isAnyPressed() end

--- Returns true while the button is currently held down.
---@param button string Button name
---@return boolean
function input.isPressed(button) end

--- Returns true if the button was pressed since the last input frame. Buttons: "back", "confirm", "left", "right",
--- "up", "down", "page_back", "page_forward".
---@param button string Button name
---@return boolean
function input.wasPressed(button) end

--- Returns true if the button was released since the last input frame.
---@param button string Button name
---@return boolean
function input.wasReleased(button) end

-- log

--- Logs a debug message to serial output.
---@param message string
function log.debug(message) end

--- Logs an error message to serial output.
---@param message string
function log.error(message) end

--- Logs an info message to serial output.
---@param message string
function log.info(message) end

-- sys

--- Blocks the app for the given number of milliseconds.
---@param ms integer
function sys.delay(ms) end

--- Requests the app to exit back to the launcher.
function sys.exit() end

--- Returns milliseconds since boot.
---@return integer
function sys.millis() end

--- Enables the on_tick() callback at a fixed interval (0 disables, minimum 33ms). Requires on_tick() to be defined.
---@param intervalMs integer 0-3600000
function sys.setTickInterval(intervalMs) end

--- Returns milliseconds since boot.
---@return integer
function sys.uptime() end

-- timer

--- Fires on_timer(id) once after the interval. Apps define on_timer(id) to receive it.
---@param intervalMs integer 100-3600000
---@param id string 1-31 letters, digits, underscores, or dashes
function timer.after(intervalMs, id) end

--- Cancels a timer by id.
---@param id string
function timer.cancel(id) end

--- Fires on_timer(id) repeatedly at the interval until cancelled.
---@param intervalMs integer 100-3600000
---@param id string 1-31 letters, digits, underscores, or dashes
function timer.every(intervalMs, id) end

-- wifi

--- Starts connecting to a stored Wi-Fi network (credentials from the reader settings). Poll wifi.status().
function wifi.connect() end

--- Disconnects Wi-Fi if the app started it.
function wifi.disconnect() end

--- Returns whether Wi-Fi is currently connected to an access point.
---@return boolean connected
function wifi.isConnected() end

--- Returns the local IP address of the Wi-Fi interface.
---@return string ip "0.0.0.0" if not connected
function wifi.localIP() end

--- Returns the Wi-Fi connection state, advancing any in-progress attempt.
---@return table status Fields state, ssid, ip and rssi. state is "disconnected", "connecting", "connected" or "failed".
function wifi.status() end

-- Callbacks a runtime app may define: draw(), on_tick(), on_button(name, state), on_timer(id).
